In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import mean_squared_error
from math import sqrt
import random
import numpy as np
random.seed(0)


dataset =  pd.read_csv("bill_authenticationWithMissingData.csv")

missing_val_count_by_column = (dataset.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0])  


Variance     8
Skewness    28
Curtosis    36
Entropy     17
dtype: int64


In [33]:
from sklearn.impute import SimpleImputer  # Imputer is for missing values
# Fill in the lines below: imputation
my_imputer = SimpleImputer(strategy='constant')  #'most_frequent' #'mean'  #'constant'  # 'median'
datasetClean = pd.DataFrame(my_imputer.fit_transform(dataset))
# Fill in the lines below: imputation removed column names; put them back
datasetClean.columns = dataset.columns
# In general you can use this imputer without worrying about the missing values.

In [34]:
# Number of missing values in each column of training data
missing_val_count_by_column = (datasetClean.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0]) 

Series([], dtype: int64)


In [35]:
X = datasetClean.drop('Class', axis=1)  # these are lectures
y = datasetClean['Class'] # these are results

from sklearn.model_selection import train_test_split  #
 #
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, shuffle=True,random_state=42)  # 80 percent training , 20 percent testing

from sklearn.svm import SVC  # support vector machine - linear
svclassifier = SVC() # kernel='linear'
fitted = svclassifier.fit(X_train, y_train)
y_pred = fitted.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
from sklearn.metrics import accuracy_score
print('SVC: %.2f%% '%  (accuracy_score(y_test, y_pred)*100))

[[228   1]
 [  3 180]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      0.99       229
         1.0       0.99      0.98      0.99       183

    accuracy                           0.99       412
   macro avg       0.99      0.99      0.99       412
weighted avg       0.99      0.99      0.99       412

SVC: 99.03% 


In [36]:
import sys
from impyute.imputation.cs import fast_knn
sys.setrecursionlimit(100000) #Increase the recursion limit of the OS

# start the KNN training
KNNimputedDataset=fast_knn(dataset.values, k=30)

In [37]:
KNNimputedDataset = pd.DataFrame(KNNimputedDataset, columns = ['Variance','Skewness','Curtosis','Entropy','Class'])

X2 = KNNimputedDataset.drop('Class', axis=1)  # these are lectures
y2 = KNNimputedDataset['Class'] # these are results

from sklearn.model_selection import train_test_split  #
 #
X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size = 0.30, shuffle=True,random_state=42)  # 80 percent training , 20 percent testing

from sklearn.svm import SVC  # support vector machine - linear
svclassifier = SVC() # kernel='linear'
fitted = svclassifier.fit(X_train, y_train)
y_pred = fitted.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
from sklearn.metrics import accuracy_score
print('SVC: %.2f%% '%  (accuracy_score(y_test, y_pred)*100))

[[228   1]
 [  5 178]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       229
         1.0       0.99      0.97      0.98       183

    accuracy                           0.99       412
   macro avg       0.99      0.98      0.99       412
weighted avg       0.99      0.99      0.99       412

SVC: 98.54% 


In [40]:
from impyute.imputation.cs import mice

# start the MICE training
miceImputerDataset=mice(dataset.values)

array([[  3.6216    ,   8.6661    ,  -2.8073    ,  -0.44699   ,
          0.        ],
       [  4.5459    ,   8.1674    ,  -2.4586    ,  -1.4621    ,
          0.        ],
       [  3.866     ,  -2.6383    ,   1.9242    ,   0.10645   ,
          0.        ],
       ...,
       [ -3.7503    , -13.4586    ,  17.5932    ,  -2.7771    ,
          1.        ],
       [ -3.5637    ,  -8.3827    ,  12.393     ,  -0.28076793,
          1.        ],
       [ -2.5419    ,  -0.65804   ,   2.6842    ,   1.1952    ,
          1.        ]])

In [42]:
miceImputerDataset = pd.DataFrame(miceImputerDataset, columns = ['Variance','Skewness','Curtosis','Entropy','Class'])

X2 = KNNimputedDataset.drop('Class', axis=1)  # these are lectures
y2 = KNNimputedDataset['Class'] # these are results

from sklearn.model_selection import train_test_split  #
 #
X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size = 0.30, shuffle=True,random_state=42)  # 80 percent training , 20 percent testing

from sklearn.svm import SVC  # support vector machine - linear
svclassifier = SVC() # kernel='linear'
fitted = svclassifier.fit(X_train, y_train)
y_pred = fitted.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
from sklearn.metrics import accuracy_score
print('SVC: %.2f%% '%  (accuracy_score(y_test, y_pred)*100))

[[228   1]
 [  5 178]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99       229
         1.0       0.99      0.97      0.98       183

    accuracy                           0.99       412
   macro avg       0.99      0.98      0.99       412
weighted avg       0.99      0.99      0.99       412

SVC: 98.54% 
