In [1]:
import numpy as np
import pandas as pd

## Dataset


https://archive.ics.uci.edu/ml/datasets/banknote+authentication

If you REEEEAAAALLLY wanna read about the data link is here above


Attribute Information:

1. variance of Wavelet Transformed image (continuous) 
2. skewness of Wavelet Transformed image (continuous) 
3. curtosis of Wavelet Transformed image (continuous) 
4. entropy of image (continuous) 
5. class (integer) 


In [2]:
data2 = pd.read_csv('bank_note_data.txt', delimiter=',')
data2.head()

3.6216  8.6661  -2.8073  -0.44699  0
0  4.54590  8.1674  -2.4586  -1.46210  0
1  3.86600 -2.6383   1.9242   0.10645  0
2  3.45660  9.5228  -4.0112  -3.59440  0
3  0.32924 -4.4552   4.5718  -0.98880  0
4  4.36840  9.6718  -3.9606  -3.16250  0

In [3]:
from numpy import genfromtxt
data = genfromtxt('bank_note_data.txt', delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:,4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

## Split the Data 

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [13]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [14]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [15]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

when using Neural Networks, you will get better performance when you use scaling the data.  just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.


In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
scaler_object = MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler()

In [19]:
scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)

Ok, now we have the data scaled!

In [21]:
X_train.max()

17.9274

In [22]:
scaled_X_train.max()

1.0000000000000002

In [23]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [24]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

## Building the NN

In [25]:
from keras.models import Sequential
from keras.layers import Dense

### Compile 

In [66]:
# Creates model
model = Sequential()
# 8 Neurons, expects input of 4 features. 
# Play around with the number of neurons!!
model.add(Dense(8, input_dim=4, activation='relu'))  #input layer
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)

model.add(Dense(8, activation='relu'))  #hidden layer
#  4-3-1
# Last layer simple sigmoid function to output 0 or 1 (our label)
model.add(Dense(1, activation='sigmoid'))  #output layer
# Play around with number of epochs as well!

In [67]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 8)                 40        
                                                                 
 dense_11 (Dense)            (None, 8)                 72        
                                                                 
 dense_12 (Dense)            (None, 1)                 9         
                                                                 
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [68]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['Accuracy'])

## Fit the model = this means training

In [69]:

model.fit(scaled_X_train,y_train,epochs=100, verbose=1)

Epoch 1/100
29/29 [==============================] - 0s 1ms/step - loss: 0.6888 - Accuracy: 0.5027
Epoch 2/100
29/29 [==============================] - 0s 1ms/step - loss: 0.6834 - Accuracy: 0.7018
Epoch 3/100
29/29 [==============================] - 0s 1ms/step - loss: 0.6764 - Accuracy: 0.7693
Epoch 4/100
29/29 [==============================] - 0s 2ms/step - loss: 0.6691 - Accuracy: 0.7737
Epoch 5/100
29/29 [==============================] - 0s 2ms/step - loss: 0.6642 - Accuracy: 0.7737
Epoch 6/100
29/29 [==============================] - 0s 2ms/step - loss: 0.6612 - Accuracy: 0.7758
Epoch 7/100
29/29 [==============================] - 0s 1ms/step - loss: 0.6586 - Accuracy: 0.7802
Epoch 8/100
29/29 [==============================] - 0s 2ms/step - loss: 0.6563 - Accuracy: 0.7791
Epoch 9/100
29/29 [==============================] - 0s 2ms/step - loss: 0.6540 - Accuracy: 0.7758
Epoch 10/100
29/29 [==============================] - 0s 2ms/step - loss: 0.6518 - Accuracy: 0.7715
Epoch 11/

Epoch 83/100
29/29 [==============================] - 0s 1ms/step - loss: 0.3039 - Accuracy: 0.9021
Epoch 84/100
29/29 [==============================] - 0s 2ms/step - loss: 0.2993 - Accuracy: 0.8999
Epoch 85/100
29/29 [==============================] - 0s 1ms/step - loss: 0.2945 - Accuracy: 0.9010
Epoch 86/100
29/29 [==============================] - 0s 1ms/step - loss: 0.2898 - Accuracy: 0.9064
Epoch 87/100
29/29 [==============================] - 0s 1ms/step - loss: 0.2854 - Accuracy: 0.9097
Epoch 88/100
29/29 [==============================] - 0s 2ms/step - loss: 0.2803 - Accuracy: 0.9086
Epoch 89/100
29/29 [==============================] - 0s 2ms/step - loss: 0.2763 - Accuracy: 0.9151
Epoch 90/100
29/29 [==============================] - 0s 2ms/step - loss: 0.2717 - Accuracy: 0.9119
Epoch 91/100
29/29 [==============================] - 0s 1ms/step - loss: 0.2673 - Accuracy: 0.9151
Epoch 92/100
29/29 [==============================] - 0s 1ms/step - loss: 0.2634 - Accuracy: 0.9173


In [70]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [71]:
# Spits out probabilities by default.
# model.predict(scaled_X_test)

In [72]:
#model.predict_classes(scaled_X_test)

predict_x=model.predict(scaled_X_test) 
classes_x=np.argmax(predict_x,axis=1)

# performance

In [73]:
model.metrics_names

['loss', 'Accuracy']

In [74]:
model.evaluate(x=scaled_X_test,y=y_test)

15/15 [==============================] - 0s 1ms/step - loss: 0.2269 - Accuracy: 0.9294


[0.22693881392478943, 0.9293597936630249]

In [76]:
from sklearn.metrics import confusion_matrix,classification_report

In [77]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")



In [78]:
confusion_matrix(y_test,predictions)

array([[248,   9],
       [ 23, 173]], dtype=int64)

In [79]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.92      0.96      0.94       257
         1.0       0.95      0.88      0.92       196

    accuracy                           0.93       453
   macro avg       0.93      0.92      0.93       453
weighted avg       0.93      0.93      0.93       453



## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [80]:
model.save('myfirstmodel.h5')

In [81]:
from keras.models import load_model

In [82]:
newmodel = load_model('myfirstmodel.h5')

In [42]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

In [43]:
data = [[-0.60254,1.7237,-2.1501,-0.77027]]   # you can also create a dataframe by yourself and feed it into  prediction
# imagine you have a banknote which has values as above. See if it can pass the authentication or not
# 1 for the pass. 0 for not-pass
  
# Create the pandas DataFrame 
df = pd.DataFrame(data, columns = ['Variance', 'Skewness','Curtosis','Entropy']) 
df

Variance  Skewness  Curtosis  Entropy
0  -0.60254    1.7237   -2.1501 -0.77027

In [44]:
predictions = (model.predict(df) > 0.5).astype("int32") # you can adjust the values and see what will your model generate.
# this is a binary classification so result will be either 1 or 0 as yes or no.
predictions

array([[0]])

In [45]:
data2 = [[6.8248,5.2187,-2.5425,0.5461],[-0.60254,1.7237,-2.1501,-0.77027]]   # you can also create a dataframe by yourself and feed it into SVM prediction
# imagine you have a banknote which has values as above. See if it can pass the authentication or not
# 1 for the pass. 0 for not-pass
  
# Create the pandas DataFrame 
df = pd.DataFrame(data2, columns = ['Variance', 'Skewness','Curtosis','Entropy']) 
df

Variance  Skewness  Curtosis  Entropy
0   6.82480    5.2187   -2.5425  0.54610
1  -0.60254    1.7237   -2.1501 -0.77027

In [46]:
predictions = (model.predict(df) > 0.5).astype("int32")  # you can adjust the values and see what will your model generate.
# this is a binary classification so result will be either 1 or 0 as yes or no.
predictions

array([[0],
       [0]])