In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset =  pd.read_csv("car.data")
#  https://archive.ics.uci.edu/ml/datasets/car+evaluation

In [3]:
dataset.head(15)

vhigh vhigh.1  2 2.1  small   low  unacc
0   vhigh   vhigh  2   2  small   med  unacc
1   vhigh   vhigh  2   2  small  high  unacc
2   vhigh   vhigh  2   2    med   low  unacc
3   vhigh   vhigh  2   2    med   med  unacc
4   vhigh   vhigh  2   2    med  high  unacc
5   vhigh   vhigh  2   2    big   low  unacc
6   vhigh   vhigh  2   2    big   med  unacc
7   vhigh   vhigh  2   2    big  high  unacc
8   vhigh   vhigh  2   4  small   low  unacc
9   vhigh   vhigh  2   4  small   med  unacc
10  vhigh   vhigh  2   4  small  high  unacc
11  vhigh   vhigh  2   4    med   low  unacc
12  vhigh   vhigh  2   4    med   med  unacc
13  vhigh   vhigh  2   4    med  high  unacc
14  vhigh   vhigh  2   4    big   low  unacc

In [4]:
dataset.shape

(1727, 7)

In [5]:
# Number of missing values in each column of training data  # no missing values you are lucky but alot of work here with 
#categorical values!
missing_val_count_by_column = (dataset.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0]) 

# https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html # another way

Series([], dtype: int64)


In [6]:
dataset.columns

Index(['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc'], dtype='object')

In [7]:
dataset.vhigh.unique()  # you can find each categorical type of column one by one. 
#dataset.yourcolumnname.unique

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [8]:
dataset.select_dtypes(include=np.number).columns.tolist() #for now you dont have any numerical column, you have work to do

[]

In [9]:
s = (dataset.dtypes == 'object')   #just another way to see all categorical columns in your data
object_cols = list(s[s].index)

print("Categorical variables:")
print(object_cols)

Categorical variables:
['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc']


In [10]:
df2 = pd.get_dummies(dataset, columns = ['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low',])
df2.head(10)

unacc  vhigh_high  vhigh_low  vhigh_med  vhigh_vhigh  vhigh.1_high  \
0  unacc           0          0          0            1             0   
1  unacc           0          0          0            1             0   
2  unacc           0          0          0            1             0   
3  unacc           0          0          0            1             0   
4  unacc           0          0          0            1             0   
5  unacc           0          0          0            1             0   
6  unacc           0          0          0            1             0   
7  unacc           0          0          0            1             0   
8  unacc           0          0          0            1             0   
9  unacc           0          0          0            1             0   

   vhigh.1_low  vhigh.1_med  vhigh.1_vhigh  2_2  ...  2_5more  2.1_2  2.1_4  \
0            0            0              1    1  ...        0      1      0   
1            0            0              1    1  ...        0      1      0   
2            0            0              1    1  ...        0      1      0   
3            0            0              1    1  ...        0      1      0   
4            0            0              1    1  ...        0      1      0   
5            0            0              1    1  ...        0      1      0   
6            0            0              1    1  ...        0      1      0   
7            0            0              1    1  ...        0      1      0   
8            0            0              1    1  ...        0      0      1   
9            0            0              1    1  ...        0      0      1   

   2.1_more  small_big  small_med  small_small  low_high  low_low  low_med  
0         0          0          0            1         0        0        1  
1         0          0          0            1         1        0        0  
2         0          0          1            0         0        1        0  
3         0          0          1            0         0        0        1  
4         0          0          1            0         1        0        0  
5         0          1          0            0         0        1        0  
6         0          1          0            0         0        0        1  
7         0          1          0            0         1        0        0  
8         0          0          0            1         0        1        0  
9         0          0          0            1         0        0        1  

[10 rows x 22 columns]

In [11]:
#lets check the target column (unacc)
dataset.unacc.unique()
#you can think of these are unaccaptable, acceptable  very good and good
#another function for that:


array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [12]:
def label_fixTarget(Ogul):
    if Ogul=='unacc':
        return 0
    elif Ogul=='acc':
        return 1
    elif Ogul=='vgood':
        return 3
    elif Ogul=="good":
        return 2  

In [13]:
df2['unacc'] = df2['unacc'].apply(label_fixTarget)


In [14]:
df2.unacc.unique()

array([0, 1, 3, 2], dtype=int64)

In [15]:
#lets see your final dataset
df2.head(15) # very clean now

unacc  vhigh_high  vhigh_low  vhigh_med  vhigh_vhigh  vhigh.1_high  \
0       0           0          0          0            1             0   
1       0           0          0          0            1             0   
2       0           0          0          0            1             0   
3       0           0          0          0            1             0   
4       0           0          0          0            1             0   
5       0           0          0          0            1             0   
6       0           0          0          0            1             0   
7       0           0          0          0            1             0   
8       0           0          0          0            1             0   
9       0           0          0          0            1             0   
10      0           0          0          0            1             0   
11      0           0          0          0            1             0   
12      0           0          0          0            1             0   
13      0           0          0          0            1             0   
14      0           0          0          0            1             0   

    vhigh.1_low  vhigh.1_med  vhigh.1_vhigh  2_2  ...  2_5more  2.1_2  2.1_4  \
0             0            0              1    1  ...        0      1      0   
1             0            0              1    1  ...        0      1      0   
2             0            0              1    1  ...        0      1      0   
3             0            0              1    1  ...        0      1      0   
4             0            0              1    1  ...        0      1      0   
5             0            0              1    1  ...        0      1      0   
6             0            0              1    1  ...        0      1      0   
7             0            0              1    1  ...        0      1      0   
8             0            0              1    1  ...        0      0      1   
9             0            0              1    1  ...        0      0      1   
10            0            0              1    1  ...        0      0      1   
11            0            0              1    1  ...        0      0      1   
12            0            0              1    1  ...        0      0      1   
13            0            0              1    1  ...        0      0      1   
14            0            0              1    1  ...        0      0      1   

    2.1_more  small_big  small_med  small_small  low_high  low_low  low_med  
0          0          0          0            1         0        0        1  
1          0          0          0            1         1        0        0  
2          0          0          1            0         0        1        0  
3          0          0          1            0         0        0        1  
4          0          0          1            0         1        0        0  
5          0          1          0            0         0        1        0  
6          0          1          0            0         0        0        1  
7          0          1          0            0         1        0        0  
8          0          0          0            1         0        1        0  
9          0          0          0            1         0        0        1  
10         0          0          0            1         1        0        0  
11         0          0          1            0         0        1        0  
12         0          0          1            0         0        0        1  
13         0          0          1            0         1        0        0  
14         0          1          0            0         0        1        0  

[15 rows x 22 columns]

In [16]:
X = df2.drop('unacc', axis=1)
y = df2['unacc']

In [17]:
cor = df2.corr()   # correlation calculation, we are trying to eliminate non-relevant columns from the dataset!
cor_target = abs(cor["unacc"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.01]  # change the parameter, to see if you can get more 
#columns related to "unacc" . In our case "type" columns looks not relevant therefore we are going to drop it!
relevant_features.index
# but what if we dont drop? we cannot guarantee that high correlation means good results!
# you can check the correlation function and see which features you can get. You can also check your bias variance trade off
# This is about the question how to find out which or how many features

Index(['unacc', 'vhigh_high', 'vhigh_low', 'vhigh_med', 'vhigh_vhigh',
       'vhigh.1_high', 'vhigh.1_low', 'vhigh.1_med', 'vhigh.1_vhigh', '2_2',
       '2_4', '2_5more', '2.1_2', '2.1_4', '2.1_more', 'small_big',
       'small_med', 'small_small', 'low_high', 'low_low', 'low_med'],
      dtype='object')

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [19]:
df2.select_dtypes(include=np.number).columns.tolist() #for now you dont have any numerical column, you have work to do

['unacc',
 'vhigh_high',
 'vhigh_low',
 'vhigh_med',
 'vhigh_vhigh',
 'vhigh.1_high',
 'vhigh.1_low',
 'vhigh.1_med',
 'vhigh.1_vhigh',
 '2_2',
 '2_3',
 '2_4',
 '2_5more',
 '2.1_2',
 '2.1_4',
 '2.1_more',
 'small_big',
 'small_med',
 'small_small',
 'low_high',
 'low_low',
 'low_med']

In [20]:
from sklearn.svm import SVC  # support vector machine - linear
svclassifier = SVC(kernel='poly')
fitted = svclassifier.fit(X_train, y_train)

In [21]:
y_pred = svclassifier.predict(X_test)

In [22]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred)) #99.999     #0.0001

[[247   0   0   0]
 [  0  68   0   0]
 [  0   0  16   0]
 [  0   0   0  15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       247
           1       1.00      1.00      1.00        68
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00        15

    accuracy                           1.00       346
   macro avg       1.00      1.00      1.00       346
weighted avg       1.00      1.00      1.00       346



In [23]:
from sklearn.metrics import accuracy_score
print('SVC:',accuracy_score(y_test, y_pred)*100,'%')

SVC: 100.0 %


In [24]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [25]:
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train,y_train)
tree_pred = decision_tree.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,tree_pred))
print(classification_report(y_test,tree_pred))

[[244   3   0   0]
 [  5  62   0   1]
 [  0   3  13   0]
 [  0   0   0  15]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       247
           1       0.91      0.91      0.91        68
           2       1.00      0.81      0.90        16
           3       0.94      1.00      0.97        15

    accuracy                           0.97       346
   macro avg       0.96      0.93      0.94       346
weighted avg       0.97      0.97      0.96       346



In [26]:
from sklearn.metrics import accuracy_score
print('DecisionTree:',accuracy_score(y_test, tree_pred)*100,'%')

DecisionTree: 96.53179190751445 %


In [27]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf_pred = rf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,rf_pred))
print(classification_report(y_test,rf_pred))

[[244   3   0   0]
 [  0  68   0   0]
 [  0   1  13   2]
 [  0   3   0  12]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       247
           1       0.91      1.00      0.95        68
           2       1.00      0.81      0.90        16
           3       0.86      0.80      0.83        15

    accuracy                           0.97       346
   macro avg       0.94      0.90      0.92       346
weighted avg       0.98      0.97      0.97       346



In [28]:
from sklearn.metrics import accuracy_score
print('Random_Forest:',accuracy_score(y_test, rf_pred)*100,'%')

Random_Forest: 97.39884393063583 %


In [29]:
KN = KNeighborsClassifier()
KN.fit(X_train,y_train)
KN_pred = KN.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,KN_pred))
print(classification_report(y_test,KN_pred))

[[244   3   0   0]
 [ 23  45   0   0]
 [  2   8   5   1]
 [  3   4   0   8]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94       247
           1       0.75      0.66      0.70        68
           2       1.00      0.31      0.48        16
           3       0.89      0.53      0.67        15

    accuracy                           0.87       346
   macro avg       0.88      0.62      0.70       346
weighted avg       0.87      0.87      0.86       346



In [30]:
from sklearn.metrics import accuracy_score
print('KNN:',accuracy_score(y_test, KN_pred)*100,'%')

KNN: 87.28323699421965 %


In [31]:
from sklearn.linear_model import LogisticRegression
regr = LogisticRegression() 
regr.fit(X_train, y_train) #training the algorithm
Log_pred = regr.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,Log_pred))
print(classification_report(y_test,Log_pred))

[[239   8   0   0]
 [  4  61   3   0]
 [  0  10   4   2]
 [  0   3   0  12]]
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       247
           1       0.74      0.90      0.81        68
           2       0.57      0.25      0.35        16
           3       0.86      0.80      0.83        15

    accuracy                           0.91       346
   macro avg       0.79      0.73      0.74       346
weighted avg       0.91      0.91      0.91       346



In [32]:
from sklearn.metrics import accuracy_score
print('youroldestFriend_Logistic_Regression:',accuracy_score(y_test, Log_pred)*100,'%')

youroldestFriend_Logistic_Regression: 91.32947976878613 %


In [33]:
print('Decision Tree:', accuracy_score(y_test, tree_pred)*100,'%') # to summarize all
print('Random Forest:', accuracy_score(y_test, rf_pred)*100,'%')
print('KNeighbors:',accuracy_score(y_test, KN_pred)*100,'%')
print('SVM:',accuracy_score(y_test, y_pred)*100,'%')

Decision Tree: 96.53179190751445 %
Random Forest: 97.39884393063583 %
KNeighbors: 87.28323699421965 %
SVM: 100.0 %


In [34]:
# Try to predict the price, you can choose any row from data set and check if the prediction "0" or "1" is correct!
test =df2.loc[[1717]]   # take Nth row to check your prediction result manually 
#in this case 1717th column in dataset is very good or 1215th is good ( you can manually compare values)
test = test.drop('unacc', axis=1)  # drop target "class" column
prediction= rf.fit(X_train,y_train).predict(test)  # you have to use rf.fit(X_train,y_train) for random forest or
# decision_tree.fit(X_train,y_train) for decision tree, YOUR FIT FUNCTION GOES THERE!
prediction

array([3], dtype=int64)

In [35]:
#now here is your new perspective, you cant always rely on numbers yea?
# here is how you can really predict your ML algorithm. you show it a NEW data and it gives you a result!
#dont forget about this part of code, you will need to check your final predictions in your career(dont worry about exam(again))

data = [[1,0,3,3,1,2,1,0,2,2,1,2,0,3,1,2,1,3,3,1,2]]   # you can also create a dataframe by yourself and feed it into SVM prediction
#very important detail look: here is my list  [[1,2,2,2,1,2]]   doubled paranthesis to have 6,1 shape for 1 vector!!!!!!!!!!
# imagine you have a banknote which has values as above. See if it can pass the authentication or not
# 1 for the pass. 0 for not-pass
  
# Create the pandas DataFrame 
dft = pd.DataFrame(data, columns = [
 'vhigh_high',
 'vhigh_low',
 'vhigh_med',
 'vhigh_vhigh',
 'vhigh.1_high',
 'vhigh.1_low',
 'vhigh.1_med',
 'vhigh.1_vhigh',
 '2_2',
 '2_3',
 '2_4',
 '2_5more',
 '2.1_2',
 '2.1_4',
 '2.1_more',
 'small_big',
 'small_med',
 'small_small',
 'low_high',
 'low_low',
 'low_med']) 


In [36]:
prediction= rf.fit(X_train,y_train).predict(dft)  # you can adjust the values and see what will your model generate.
# this is a binary classification so result will be either 1 or 0 as yes or no.
prediction

array([0], dtype=int64)