In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset =  pd.read_csv("car.data")

In [3]:
# original column names   
#buying,main,doors,persons,lug_boot,safety,class
#'vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc'

In [4]:
dataset.head(5)

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [5]:
dataset.shape

(1727, 7)

In [6]:
# Number of missing values in each column of training data  # no missing values you are lucky but alot of work here with 
#categorical values!
missing_val_count_by_column = (dataset.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0]) 

Series([], dtype: int64)


In [7]:
dataset.columns

Index(['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc'], dtype='object')

In [8]:
dataset.vhigh.unique()  # you can find each categorical type of column one by one. 
#dataset.yourcolumnname.unique

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [9]:
dataset.select_dtypes(include=np.number).columns.tolist() #for now you dont have any numerical column, you have work to do

[]

In [10]:
s = (dataset.dtypes == 'object')   #just another way to see all categorical columns in your data
object_cols = list(s[s].index)

print("Categorical variables:")
print(object_cols)

Categorical variables:
['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc']


In [11]:
from sklearn.preprocessing import LabelEncoder
# Apply label encoder 
label_encoder = LabelEncoder()
dataset.vhigh = label_encoder.fit_transform(dataset.vhigh)  # we can use label encoder to automatically assign an
#integer instead of categorical variables. Remember, you cannot use categorical variables, you need numerical dataset 
#in order to implement your Machine Learning models properly.
# there are other methods, such as completely remove the column which is not suggested,
# one other way is one hot encoder

In [12]:
dataset.vhigh.unique()  # Labelencoder is better than your boyfriend or girlfriend, it gives you the power of transforming those
#ugly characters to computer-friendly numerical values.(also no cheating-no complaining)
# in your vhigh column you have ['vhigh', 'high', 'med', 'low'] now transforms into [3,2,1,0] thats it! # we can use label encoder to automatically assign an
#integer instead of categorical variables. Remember, you cannot use categorical variables, you need numerical dataset 
#in order to implement your Machine Learning models properly.
# there are other methods, such as completely remove the column which is not suggested,
# one other way is one hot encoder

array([3, 0, 2, 1])

In [13]:
dataset["vhigh.1"].unique() # we can do the same encoder thing here again for vhigh.1 column

array(['vhigh', 'high', 'med', 'low'], dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder
# Apply label encoder 
label_encoder = LabelEncoder()
dataset["vhigh.1"] = label_encoder.fit_transform(dataset["vhigh.1"]) 

In [15]:
dataset["vhigh.1"].unique()


array([3, 0, 2, 1])

In [16]:
dataset["2"].unique()  #whops here is complicataed stuff computer cannot understand what is 5more, 
# you can change the name or do like this:
# here is my solution to this problem MANUALLY

array(['2', '3', '4', '5more'], dtype=object)

In [17]:
aa='Atlanta'
def label_fix(Ogul):
    if Ogul=='2':
        return 2
    elif Ogul=='3':
        return 3
    elif Ogul=='4':
        return 4
    else:
        return 5

In [18]:
dataset['2'] = dataset['2'].apply(label_fix)
dataset['2'].unique() 

array([2, 3, 4, 5], dtype=int64)

In [19]:
dataset

vhigh  vhigh.1  2   2.1  small   low  unacc
0         3        3  2     2  small   med  unacc
1         3        3  2     2  small  high  unacc
2         3        3  2     2    med   low  unacc
3         3        3  2     2    med   med  unacc
4         3        3  2     2    med  high  unacc
...     ...      ... ..   ...    ...   ...    ...
1722      1        1  5  more    med   med   good
1723      1        1  5  more    med  high  vgood
1724      1        1  5  more    big   low  unacc
1725      1        1  5  more    big   med   good
1726      1        1  5  more    big  high  vgood

[1727 rows x 7 columns]

In [20]:
dataset['2.1'].unique() # again the same problem write another function:
# I have a philosophical question to you: How can you define more mathematically?
# putting here 5 6 7 or something else can affect your result
#my recomendation: try different numbers and see hows your accuracy!!! 
#lets choose 6

array(['2', '4', 'more'], dtype=object)

In [21]:
def label_fix2(Ogul):
    if Ogul=='2':
        return 2
    elif Ogul=='4':
        return 4
    else:
        return 6

In [22]:
dataset['2.1'] = dataset['2.1'].apply(label_fix2)

In [23]:
dataset['2.1'].unique()

array([2, 4, 6], dtype=int64)

In [24]:
dataset["small"].unique() # this one is easy you can also use simple encoder again

array(['small', 'med', 'big'], dtype=object)

In [25]:
from sklearn.preprocessing import LabelEncoder


# Apply label encoder 

label_encoder = LabelEncoder()
dataset.small = label_encoder.fit_transform(dataset.small)

In [26]:
dataset["small"].unique()

array([2, 1, 0])

In [27]:
dataset["low"].unique() #another simple encoding

array(['med', 'high', 'low'], dtype=object)

In [28]:
from sklearn.preprocessing import LabelEncoder


# Apply label encoder 

label_encoder = LabelEncoder()
dataset.low = label_encoder.fit_transform(dataset.low)

In [29]:
dataset["low"].unique()

array([2, 0, 1])

In [30]:
#lets check the target column (unacc)
dataset.unacc.unique()
#you can think of these are unaccaptable, acceptable  very good and good
#another function for that:


array(['unacc', 'acc', 'vgood', 'good'], dtype=object)

In [31]:
def label_fixTarget(Ogul):
    if Ogul=='unacc':
        return 0
    elif Ogul=='acc':
        return 1
    elif Ogul=='vgood':
        return 3
    elif Ogul=="good":
        return 2  

In [32]:
dataset['unacc'] = dataset['unacc'].apply(label_fixTarget)


In [33]:
dataset.unacc.unique()

array([0, 1, 3, 2], dtype=int64)

In [34]:
#lets see your final dataset # very clean now
dataset.head(20) 

vhigh  vhigh.1  2  2.1  small  low  unacc
0       3        3  2    2      2    2      0
1       3        3  2    2      2    0      0
2       3        3  2    2      1    1      0
3       3        3  2    2      1    2      0
4       3        3  2    2      1    0      0
5       3        3  2    2      0    1      0
6       3        3  2    2      0    2      0
7       3        3  2    2      0    0      0
8       3        3  2    4      2    1      0
9       3        3  2    4      2    2      0
10      3        3  2    4      2    0      0
11      3        3  2    4      1    1      0
12      3        3  2    4      1    2      0
13      3        3  2    4      1    0      0
14      3        3  2    4      0    1      0
15      3        3  2    4      0    2      0
16      3        3  2    4      0    0      0
17      3        3  2    6      2    1      0
18      3        3  2    6      2    2      0
19      3        3  2    6      2    0      0

In [35]:
cor = dataset.corr()   # correlation calculation, we are trying to eliminate non-relevant columns from the dataset!
cor_target = abs(cor["unacc"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.01]  # change the parameter, to see if you can get more 
#columns related to "unacc" . 
relevant_features.index
# but what if we dont drop? we cannot guarantee that high correlation means good results!
# you can check the correlation function and see which features you can get. You can also check your bias variance trade off
# This is about the question how to find out which or how many features

Index(['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc'], dtype='object')

In [36]:
X = dataset.drop('unacc', axis=1)
y = dataset['unacc']

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [38]:
from sklearn.svm import SVC  # support vector machine - linear
svclassifier = SVC(kernel='poly')
fitted = svclassifier.fit(X_train, y_train)

In [39]:
y_pred = svclassifier.predict(X_test)

In [40]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred)) #99.999     #0.0001

[[237  11   0   0]
 [ 29  39   2   3]
 [  4   7   2   0]
 [  2   2   0   8]]
              precision    recall  f1-score   support

           0       0.87      0.96      0.91       248
           1       0.66      0.53      0.59        73
           2       0.50      0.15      0.24        13
           3       0.73      0.67      0.70        12

    accuracy                           0.83       346
   macro avg       0.69      0.58      0.61       346
weighted avg       0.81      0.83      0.81       346



In [41]:
from sklearn.metrics import accuracy_score
print('SVC:',accuracy_score(y_test, y_pred)*100,'%')

SVC: 82.65895953757226 %


In [42]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [43]:
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train,y_train)
tree_pred = decision_tree.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,tree_pred))
print(classification_report(y_test,tree_pred))

[[245   3   0   0]
 [  0  73   0   0]
 [  0   1  12   0]
 [  0   0   0  12]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       248
           1       0.95      1.00      0.97        73
           2       1.00      0.92      0.96        13
           3       1.00      1.00      1.00        12

    accuracy                           0.99       346
   macro avg       0.99      0.98      0.98       346
weighted avg       0.99      0.99      0.99       346



In [44]:
from sklearn.metrics import accuracy_score
print('DecisionTree:',accuracy_score(y_test, tree_pred)*100,'%')

DecisionTree: 98.84393063583815 %


In [45]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf_pred = rf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,rf_pred))
print(classification_report(y_test,rf_pred))

[[243   5   0   0]
 [  0  73   0   0]
 [  0   0  13   0]
 [  0   1   0  11]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       248
           1       0.92      1.00      0.96        73
           2       1.00      1.00      1.00        13
           3       1.00      0.92      0.96        12

    accuracy                           0.98       346
   macro avg       0.98      0.97      0.98       346
weighted avg       0.98      0.98      0.98       346



In [46]:
from sklearn.metrics import accuracy_score
print('Random_Forest:',accuracy_score(y_test, rf_pred)*100,'%')

Random_Forest: 98.26589595375722 %


In [47]:
KN = KNeighborsClassifier()
KN.fit(X_train,y_train)
KN_pred = KN.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,KN_pred))
print(classification_report(y_test,KN_pred))

[[243   5   0   0]
 [ 31  42   0   0]
 [  2   6   5   0]
 [  0   5   1   6]]
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       248
           1       0.72      0.58      0.64        73
           2       0.83      0.38      0.53        13
           3       1.00      0.50      0.67        12

    accuracy                           0.86       346
   macro avg       0.86      0.61      0.69       346
weighted avg       0.85      0.86      0.84       346



In [48]:
from sklearn.metrics import accuracy_score
print('KNN:',accuracy_score(y_test, KN_pred)*100,'%')

KNN: 85.54913294797689 %


In [49]:
from sklearn.linear_model import LogisticRegression
regr = LogisticRegression() 
regr.fit(X_train, y_train) #training the algorithm
Log_pred = regr.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,Log_pred))
print(classification_report(y_test,Log_pred))

[[227  20   0   1]
 [ 51  15   0   7]
 [ 12   1   0   0]
 [  5   4   0   3]]
              precision    recall  f1-score   support

           0       0.77      0.92      0.84       248
           1       0.38      0.21      0.27        73
           2       0.00      0.00      0.00        13
           3       0.27      0.25      0.26        12

    accuracy                           0.71       346
   macro avg       0.35      0.34      0.34       346
weighted avg       0.64      0.71      0.66       346



D:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `z

In [50]:
from sklearn.metrics import accuracy_score
print('youroldestFriend_Logistic_Regression:',accuracy_score(y_test, Log_pred)*100,'%')

youroldestFriend_Logistic_Regression: 70.8092485549133 %


In [51]:
#old friends may betray you sometimes

In [52]:
print('Decision Tree:', accuracy_score(y_test, tree_pred)*100,'%') # to summarize all
print('Random Forest:', accuracy_score(y_test, rf_pred)*100,'%')
print('KNeighbors:',accuracy_score(y_test, KN_pred)*100,'%')
print('SVM:',accuracy_score(y_test, y_pred)*100,'%')

Decision Tree: 98.84393063583815 %
Random Forest: 98.26589595375722 %
KNeighbors: 85.54913294797689 %
SVM: 82.65895953757226 %


In [53]:
# Try to predict the price, you can choose any row from data set and check if the prediction "0" or "1" is correct!
test =dataset.loc[[1717]]   # take Nth row to check your prediction result manually 
#in this case 1717th column in dataset is very good or 1215th is good ( you can manually compare values)
test = test.drop('unacc', axis=1)  # drop target "class" column
prediction= rf.fit(X_train,y_train).predict(test)  # you have to use rf.fit(X_train,y_train) for random forest or
# decision_tree.fit(X_train,y_train) for decision tree, YOUR FIT FUNCTION GOES THERE!
prediction

array([3], dtype=int64)

In [54]:
#now here is your new perspective, you cant always rely on numbers yea?
# here is how you can really predict your ML algorithm. you show it a NEW data and it gives you a result!
#dont forget about this part of code, you will need to check your final predictions in your career(dont worry about exam(again))

data = [[1,0,3,3,1,2]]   # you can also create a dataframe by yourself and feed it into SVM prediction
#very important detail look: here is my list  [[1,2,2,2,1,2]]   doubled paranthesis to have 6,1 shape for 1 vector!!!!!!!!!!
# imagine you have a banknote which has values as above. See if it can pass the authentication or not
# 1 for the pass. 0 for not-pass
  
# Create the pandas DataFrame 
df = pd.DataFrame(data, columns = ['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low']) 
df

vhigh  vhigh.1  2  2.1  small  low
0      1        0  3    3      1    2

In [55]:
prediction= rf.fit(X_train,y_train).predict(df)  
prediction

array([0], dtype=int64)