### 1. Run the following cells: use these arrays for taskks

In [2]:
import numpy as np

In [3]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [4]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [5]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Slice the first column of the 2-D array. 

In [17]:
array_2D[:,0]

array([20, 43, 11])

### 3. Slice the last column of the 2-D array

In [6]:
array_2D[:,-1]

array([60, 87, 55])

### 4. Slice the second row of the 2-D array

In [7]:
array_2D[1]

array([43, 54, 65, 76, 87])

### 5. Slice the last two columns of the 2-nd row of the 2-D array

In [8]:
array_2D[:,-2:]

array([[50, 60],
       [76, 87],
       [44, 55]])

### 6. Slice the 1st, 3rd and 5th columns of the 2-D array
   (<b>Hint</b>: Take advantage of the [start:stop:step] sYntax of indices)

In [9]:
array_2D[:,0:5:2]

array([[20, 40, 60],
       [43, 65, 87],
       [11, 33, 55]])

### 9. Generate 4 arrays of size 12:
    A) The first one should be "empty"
    B) The second one should be full of 0s
    C) The third one should be full of 1s
    D) The last one should be full of 50s


In [12]:
arr_empty = np.empty(12)
arr_empty

array([1.28707904e-311, 2.51973479e-322, 0.00000000e+000, 0.00000000e+000,
       1.89146896e-307, 1.16095484e-028, 8.30807897e+151, 2.73417303e-052,
       1.46899930e+179, 9.08367237e+223, 1.16466228e-028, 1.40855697e-075])

In [13]:
arr_zeros = np.zeros(12, dtype=int)
arr_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
arr_ones = np.ones(12, dtype=int)
arr_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [75]:
arr_50s = np.full(12, 50, dtype=int)
arr_50s

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

### 10. Generate 4 more arrays. This time, they should be 2 by 4 arrays. 

In [38]:
ar_2D = np.array([], ndmin=2)

In [39]:
ar_3D = np.zeros([12,12,12])

In [40]:
ar_4D = np.ones([12,12,12,12])

### 11. With the help of the np.arange() function, generate several sequences of numbers:
    A) The integers from 0 to 50, 
    B) The integers from 1 to 50, 
    C) The integers from 25 to 50,, 
    D) Every 5-th integers from 25 to 50, including 50. 

In [42]:
arr_a = np.arange(50)
arr_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [46]:
arr_b = np.arange(1,50)
arr_b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
arr_c = np.arange(25,50)
arr_c

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
arr_d = np.arange(20, 50+1, 5)
arr_d

array([20, 25, 30, 35, 40, 45, 50])

### 12. Import the following functions from the numpy.random module:
    A) Generator as "gen".
    B) PCG64 as "pcg"

In [60]:
from numpy.random import default_rng

In [61]:
from numpy.random import Generator as gen

In [62]:
from numpy.random import PCG64 as pcg

### 13. Create a random generator object.

In [68]:
gen_obj = gen(pcg())

In [69]:
gen_obj2 = gen(pcg())

### 14. Using the .random() method, generate your array with your array size

In [ ]:
# preferably impressive random numbers here

In [71]:
arr_1 = gen_obj.integers(1,20,5)
arr_1

array([11,  5,  6,  4,  3], dtype=int64)

In [72]:
arr_2 = gen_obj.random(10)
arr_2

array([0.31970992, 0.73890669, 0.25077017, 0.80369568, 0.28106804,
       0.31199888, 0.69516284, 0.5172075 , 0.58683655, 0.65986586])

In [74]:
arr_3 = gen_obj2.choice(arr_1, 3)
arr_3

array([11,  5, 11], dtype=int64)

In [75]:
arr_4 = gen_obj2.bytes(10)
arr_4

b'\x83\x80\xe4.-70\x82\x8d\x94'