In [15]:
import numpy as np# your favorite part

## Indexing

In [16]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

### Specific Values

In [17]:
array_a[1]

## By adding numbers between square brackets, we can reference specific values of the array. 
## Python uses 0-indexing, so the first position has an index 0, the second position has index 1, and so on.

array([4, 5, 6])

In [18]:
array_a[1][2]

## We can index every dimension of the array separately. 

6

In [19]:
array_a[1,0]

## [1,0] is equivalent to [1][0] 

4

In [20]:

array_a[:,2]

## The ":" is equivalent to "from start to end" in this context. 

array([3, 6])

### Negative Indices

In [21]:
array_b = np.array([1,2,3])
array_b[-1]

## Negative indices mean traversing from the back. 
## No such thing as  -0 , so the first negative index is -1.

3

In [25]:
array_a[-1,-1]

6

In [8]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array_a[-1]

array([4, 5, 6])

In [10]:
# array_a[-3] 
# Goes out of bounds, since -3 implies there are 3 rows. 

## Assigning Values

In [11]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array_a[0,2] = 9
array_a 

## Assign a value to an individual element.

array([[1, 2, 9],
       [4, 5, 6]])

In [13]:
array_a[0] = 9
array_a

## Assign a value to an entire row.

array([[9, 9, 9],
       [4, 5, 6]])

In [8]:
array_a[:,0] = 9
array_a

## Assign a value to an entire column.

array([[9, 2, 3],
       [9, 5, 6]])

In [29]:
list_a = [8,7,8]
x = np.array([[1,2,3],[3,4,4]])
x[1] = list_a
x

## Assign different values to an entire row via a list. 

C:\Users\MONSTER\AppData\Local\Temp/ipykernel_14112/2139490230.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([[1,2,3],[3,4,4,5,]])


array([list([1, 2, 3]), list([8, 7, 8])], dtype=object)

In [16]:
type(array_a[0])

numpy.ndarray

In [30]:
array_a[:] = 55
array_a

## Assign the same value to all the individual elements in the array.

array([[55, 55, 55],
       [55, 55, 55]])

In [31]:
array_a = 9
array_a

## Type assignment in Python is dynamic. Hence, a variable's type can change based on what values we assign to it. 
## Here, array_a changes from an ndarray to an integer.

9

In [19]:
type(array_a)

int

In [20]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Elementwise Properties

In [21]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [22]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
array_b + 2

## Multiplying each element of array_b by 2

array([3, 4, 5])

In [32]:
list_a = [1,2,3]
list_a * [2]

## Since lists don't work elementwise, we're concatenating [2] to list_a.

TypeError: can only concatenate list (not "int") to list

In [25]:
array_a + 2

## Elementwise addition adds 2 to each element of array_a.

array([ 9, 10, 11])

In [26]:
array_a * array_b[1]

## Elementwise multiplication. 
## We multiply each individual element of array_a by its corresponding element in the second row of array_b.

array([28, 40, 54])

In [27]:
array_b - array_a

## The order of the elements matters for elementwise subtraction, division, as well as other operations. 

array([[-6, -6, -6],
       [-3, -3, -3]])

## Types of Data Supported by NumPy

In [4]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float64)  # half mem float
array_a

# Defining all the values as floats (decimals).

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a

# Defining all the values as complex numbers.

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [31]:
array_a = np.array([[1,2,0],[4,5,6]], dtype = np.bool)
array_a

# Defining all the values as Booleans.

array([[ True,  True, False],
       [ True,  True,  True]])

In [13]:
array_a = np.array([[1111,2222,3333],[4444,5555,6666]], dtype = np.str)  # coerce, avoid all non numeric and ignore, continue
# calculation with numeric elements
array_a 

# Defining all the values as text.

C:\Users\MONSTER\AppData\Local\Temp/ipykernel_11540/3066241552.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a = np.array([[1111,2222,3333],[4444,5555,6666]], dtype = np.str)


array([['1111', '2222', '3333'],
       ['4444', '5555', '6666']], dtype='<U4')

https://numpy.org/devdocs/reference/generated/numpy.dtype.kind.html <- <i> A link to the documentation explaining the unicode abbreviation.

In [34]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [16]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [17]:
matrix_C = np.array([[1,2,3],[4,5,6]])
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.add(array_b, matrix_C)

## Adding up values, even though the arrays don't have matching shapes. 

array([[2, 3, 4],
       [6, 7, 8]])

In [19]:
np.add(array_b, matrix_C, dtype = np.float64)

## We can define the datatyep

array([[2., 3., 4.],
       [6., 7., 8.]])

In [39]:
np.mean(matrix_C, axis = 1)

## Axis = 0 runs the function over every column. 
## Axis = 1 runs the function over every row. 

array([2., 5.])

In [40]:
matrix_C 

array([[1, 2, 3],
       [4, 5, 6]])